services:
  inception-server:
    build: ./requirements/nginx
    image: inception-server
    ports:
      - "8080:443"
  inception-wp:
    build: ./requirements/wordpress
    image: inception-wp
    ports:
      - "9000:9000"
