services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    ports:
      - ":3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATA_PATH: /var/lib/mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 30
    networks:
      - inception-network
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    ports:
      - ":9000"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: mariadb:3306
      WP_DATA_PATH: /var/www/html/wordpress
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_EDITOR_USER: ${WP_EDITOR_USER}
      WP_EDITOR_PASSWORD: ${WP_EDITOR_PASSWORD}
      WP_EDITOR_EMAIL: ${WP_EDITOR_EMAIL}
    networks:
      - inception-network
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    restart: always
    environment:
      - COUNTRY
      - STATE
      - ORGANIZATION
      - CERT_NAME
      - DOMAIN_NAME
      - RSA_KEY_NUMBITS
    networks:
      inception-network:
        aliases:
          - ${DOMAIN_NAME}

networks:
  inception-network:

volumes:
  wp_data:
  db_data:
