services:
  inception-db:
    build: ./requirements/mariadb
    image: inception-db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  inception-wp:
    build: ./requirements/wordpress
    image: inception-wp
    ports:
      - "9000:9000"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - inception-db
    restart: always
    environment:
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_HOST: inception-db:3306
  inception-server:
    build: ./requirements/nginx
    image: inception-server
    ports:
      - "8080:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - inception-wp
    restart: always

volumes:
  wp_data:
  db_data:
