services:
  inception-db:
    build: ./requirements/mariadb
    image: inception-db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATA_PATH: /var/lib/mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  inception-wp:
    build: ./requirements/wordpress
    image: inception-wp
    ports:
      - "9000:9000"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      inception-db:
        condition: service_healthy
    restart: always
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: inception-db:3306
      WP_DATA_PATH: /var/www/html/wordpress
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_EDITOR_USER: ${WP_EDITOR_USER}
      WP_EDITOR_PASSWORD: ${WP_EDITOR_PASSWORD}
      WP_EDITOR_EMAIL: ${WP_EDITOR_EMAIL}
  inception-server:
    build: ./requirements/nginx
    image: inception-server
    ports:
      - "8080:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - inception-wp
    restart: always

volumes:
  wp_data:
  db_data:
